services:
  mongo:
    image: mongo:latest
    container_name: mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  minio:
    image: minio/minio:latest
    container_name: minio_dev
    ports:
      - "9000:9000"
      - "9090:9090"  # Consola web
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    volumes:
      - ./minio_data:/data
