version: "3.8"
services:
  app:
    image: python:3.11-slim
    container_name: whispai_app
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    env_file:
      - .env
    depends_on:
      - mongodb
      - minio

  mongodb:
    image: mongo:6.0
    container_name: whispai_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=whispai

  minio:
    image: minio/minio:latest
    container_name: whispai_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
