services:
  app:
    build: .
    container_name: whispai_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:6.0
    container_name: whispai_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: whispai_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped


volumes:
  mongo_data:
  minio_data: