version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: whispai_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../.env.docker
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - whispai_net

volumes:
  rabbitmq_data:

networks:
  whispai_net:
    external: true
